name: Checked C Clang Macro Sanity Tests

on:
  push:
    branches:
      - 'main'
    pull_request:
        branches:
            - 'main'
            - 'master'

env:
  builddir: "${{github.workspace}}/b/ninja"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}/b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH: "x86_64"
  TEST_SUITE: "CheckedC_clang"

jobs:
  # Cleanup files left behind by prior runs
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -rf ${{env.builddir}}
          mkdir -p ${{env.builddir}}
          rm -rf ${{env.BUILD_BINARIESDIRECTORY}}
          mkdir -p ${{env.BUILD_BINARIESDIRECTORY}}
          rm -rf ${{env.BUILD_SOURCESDIRECTORY}}
          mkdir -p ${{env.BUILD_SOURCESDIRECTORY}}

  build:
    name: Build Checked C Clang
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}
         ./clang/automation/UNIX/build-and-test.sh