name: Checked C Clang Macro Sanity Tests

on:
  push:
    branches:
      - 'main'
    pull_request:
        branches:
            - 'main'
            - 'master'

env:
  builddir: "${{github.workspace}}/b/ninja"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}/b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH: "X86_64"
  RUN_LOCAL:  "no"
jobs:
  # Cleanup files left behind by prior runs
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -rf ${{env.builddir}}
          mkdir -p ${{env.builddir}}
          rm -rf ${{env.BUILD_BINARIESDIRECTORY}}
          mkdir -p ${{env.BUILD_BINARIESDIRECTORY}}
          rm -rf ${{env.BUILD_SOURCESDIRECTORY}}
          mkdir -p ${{env.BUILD_SOURCESDIRECTORY}}

  test Clang checkedc [UNIX]:
    TEST_SUITE: "CheckedC_clang"
    name: Build and test Checked C Clang on UNIX
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
         ./build-and-test.sh

  test Clang ALL [UNIX]:
    TEST_SUITE: "CheckedC_LLVM"
    name: Build and test Checked C Clang and LLVM on UNIX
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
         ./build-and-test.sh

  test CheckedC tests [UNIX]:
    TEST_SUITE: "CheckedC-tests"
    name: Build Checked C clang and test only checkedc tests on UNIX
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
         ./build-and-test.sh

  test CheckedC on windows  [Windows]:
    TEST_SUITE: "CheckedC_clang"
    name: Build Checked C clang and test only checkedc tests on windows
    needs: clean
    runs-on: windows-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
         chdir ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
         cmd.exe /c 'build-and-test.bat'

  test Clang ALL [Windows]:
    TEST_SUITE: "CheckedC_LLVM"
    name: Build and test Checked C Clang and LLVM on windows
    needs: clean
    runs-on: windows-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
          chdir ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
          cmd.exe /c 'build-and-test.bat'

  test CheckedC tests [Windows]:
    TEST_SUITE: "CheckedC-tests"
    name: Build Checked C clang and test only checkedc tests on windows
    needs: clean
    runs-on: windows-latest
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run setup-and-test.sh script
        run: |
          chdir ${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/
          cmd.exe /c 'build-and-test.bat'
