name: Checked C Clang Macro Sanity Tests

on:
  push:
    branches:
      - 'main'
    pull_request:
        branches:
            - 'main'
            - 'master'

env:
  builddir: "${{github.workspace}}/b/ninja"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}/b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH: "x86_64"
  TEST_SUITE: "CheckedC_clang"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run shell script
        uses: actions/checkout@v2
        run: sh .${{env.BUILD_SOURCESDIRECTORY}}/clang/automation/UNIX/setup-and-test.sh