name: Checked C Clang Macro Sanity Tests

on:
  push:
    branches:
      - 'main'
    pull_request:
        branches:
            - 'main'
            - 'master'

env:
  builddir: "${{github.workspace}}/b/ninja"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}/b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH: "x86_64"
  TEST_SUITE: "CheckedC_clang"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}

      - name: Run shell script
        run: |
         cd ${pwd}
         sh ./clang/automation/UNIX/setup-and-test.sh